[package]
name = "k-nucleotide"
version = "0.1.0"
authors = ["Andrew Champion <andrew.champion@gmail.com>"]

[dependencies]
lazy_static = "0.1.*"

[[bin]]
name = "k-nucleotide"
path = "k-nucleotide.rs"
